### ISSUE TITLE
fan

### ISSUE THREAD

**Issue by velidhu** [kad/Marlin#10]
can you tell me how to enable the extruder fan which starts working when the extruder temperature reaches 50 °

**Comment by kad** [comment]
You need to have firmware that is marked with e0fan in the filename. That would control fan labeled on SKR boards as CNC_FAN2 as automatic extruder fan. You would need to re-wire hotend fan from "always-on" connector to CNC_FAN2

**Comment by ckiefer** [comment]
@kad That is helpful. 
On my SKR mini E3 V2.0 board I see locations 'FAN0' and 'FAN1', but I don't see a spot labelled 'CNC_FAN2'.

**Comment by kad** [comment]
@ckiefer yes, on E3 fans are done differently, thus SKR mini E3 has different labels.
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/hardware/BTT%20SKR%20MINI%20E3%20V2.0/Hardware/BTT%20SKR%20MINI%20E3%20V2.0-PIN.pdf 
FAN0 (PC6) is for part cooling, FAN1 (PC7) by default Controller Fan or in `e0fan` - extruder automatic fan.
