### ISSUE TITLE
Speed according to the LCD

### ISSUE THREAD

**Issue by tocguy** [kad/Marlin#16]
I've noticed that regardless of the speed settings selected during slicing (latest Cura) that the AMZ2 unit's LCD always shows the speed as 100.

**Comment by pappicio** [comment]
the speed on lcd is 100%, not 100 mm/s.... if on cura you have 100mm/s, and on display you change to 150 (%), the print speed increases to 150mm/s.

**Comment by kad** [comment]
Yes, as @pappicio said, on LCD it displays speed as 100%. While printing from SD card you can by rotating increase it proportionally (150-200%).
