### ISSUE TITLE
Build Varients Wiki

### ISSUE THREAD

**Issue by Vicarious111** [kad/Marlin#20]
The build variants wiki is not using the current build abbreviations.  While they can still be (mostly) figured out, they can be confusing.

**Comment by Kirottu** [comment]
Yeah i have noticed, I for one would like to get manual mesh bed leveling on my original AMZ but I don't know which one of them is the right one as the naming scheme has been changed.

**Comment by Bischi1997** [comment]
I asked in the [AMZ sub](https://www.reddit.com/r/AnycubicMegaZero/). The right version with manual bed leveling for the AMZ 1.0 with the original melzi board version should be the following: [amz_melzi-2.0.9.1-kad1-firmware.hex](https://github.com/kad/Marlin/releases/download/v2.0.9.1-kad1/amz_melzi-2.0.9.1-kad1-firmware.hex)

If I understood correctly the abbreviations stand for the following:
akp -> allen key probe
bl -> BLTouch
bfpt -> BFPTouch
PINDA  -> PINDA sensor

The other abbreviations are explained in the [Leveling Sensors Wiki](https://github.com/kad/Marlin/wiki/Leveling-sensors)

If I missed something, let me know :)

**Comment by kad** [comment]
Build variants page is updated. If there are comments or suggestions, please speakup :)
