### ISSUE TITLE
Enable WIFI SKR MINI E3 V2 + TFT35 E3

### ISSUE THREAD

**Issue by bubulgum** [kad/Marlin#28]
Hi. How to enable wifi support with ESP8266-01 01S WIFI on the TFT?
I had setup ESP3D.
Using env:"anycubic_mega_zero2_btt_mini_bl"
If #define ESP3D_WIFISUPPORT i have ERR: #error "ESP3D_WIFISUPPORT or WIFISUPPORT requires an ESP32 MOTHERBOARD."
Or i do SMTH wrong?

**Comment by kad** [comment]
You don't need to do anything on the main board for that. esp3d wifi on the tft side uses same serial port that tft is using in "touch" mode.
