### ISSUE TITLE
Can't change D-Value in PID-Tune for Heated-Bed

### ISSUE THREAD

**Issue by Haerteleric** [kad/Marlin#35]
I'm using the amz_melzi_bed-2.0.9.2-kad1-firmware.hex 
If i try to set a D-Value for the heated Bed PID-Controll, the value just resets after i confirm.

**Comment by kad** [comment]
I think all of this related to EEPROM issue in 2.0.9.2 for STM32 HAL. Not visible in `maple` variant.
Please upgrade to `2.0.9.3`.
