### ISSUE TITLE
PID: I and D settings for Bed and Hotend are swapped!

### ISSUE THREAD

**Issue by marsmol80** [kad/Marlin#42]
### Description
PID: I and D settings for Bed and HotEnd are swapped when set through printer menu.
Adjusting them and then either loading from or saving to EEPROM causes failure.

I think this is also what happens in #35 , and it might be the cause of #41

**Comment by kad** [comment]
I think all of this related to EEPROM issue in 2.0.9.2 for STM32 HAL. Not visible in `maple` variant.
Please upgrade to `2.0.9.3`.

**Comment by marsmol80** [comment]
Thank you, this indeed solved the issue.
