### ISSUE TITLE
"No Printer Attached!" after flashing. 

### ISSUE THREAD

**Issue by WarMacre** [kad/Marlin#44]
I'm not able to get any of the firmware to work with my SKR Mini MZ v1.0 MZ2.0. It fails to connect to the printer with the message "No Printer Attached!". I've tried both maple and non-maple versions without success.

**Comment by kad** [comment]
You mean with BTT TFT? my configs have serial speed 250000 where BTT TFT defaults to 115200. Please try to update baudrate on TFT settings.

**Comment by WarMacre** [comment]
Yeah, I have the BTT TFT35 v3.0. I had a suspicion it was the baud rate, and if the default baud speed in the build is 115200 then that would explain it. Many thanks!

**Comment by WarMacre** [comment]
Changing the connection speed to 25,000 fixed the issue.
