### ISSUE TITLE
TFT35 E3 V3.0 stops printing

### ISSUE THREAD

**Issue by godl3ss** [kad/Marlin#47]
Installed the latest kad marlin 2.0.9 on my MZ2 with BTT SKR MINI MZ, BL TOUCH and TFT35 E3 V3.0.
SD Card onboard recognized but doesn't show files in directories
Only able to print from TFT SD but most of the times the print stops randomly.

If i mount back the LCD everything works perfectly.

Is there a way to fix this on my configuration?
Thanks in advance

**Comment by godl3ss** [comment]
update: i tried to print in marlin mode emulation and it works since it prints from onboard SD. Printing in touch mode from TFT SD fails 90% of times randomly

**Comment by kad** [comment]
Printing from TFT means that firmware on TFT is reading gcode file and feeds line-by-line to motherboard over serial port. Random stop printing might be caused either communication error over that serial port or firmware problems (reading/parsing files from TFT SD card) on TFT side. Did you update TFT firmware to the latest one?

For serial communication issues, the only possible way that I see is to drop speed between board/tft to 115200 from current 250000.
