### ISSUE TITLE
Config files location

### ISSUE THREAD

**Issue by Riconec** [kad/Marlin#49]
Hi! I was wondering about which featureset is enabled for AMZ2 with stock board but haven't found config and config_adv files to check. Board have not enough memory so I am worried it doesn't have linear advance

**Comment by kad** [comment]
Configs are in usual place `Marlin/Configuration*.h`, however you need to look at corresponding branch. e.g. https://github.com/kad/Marlin/blob/anycubic-kad-bugfix-2.1.x/Marlin/Configuration.h

As for feature set, it all depends on the compilation target and board. Single config set is used for all features, but based on board/model things are geting enabled/disabled dynamically. Linear advance is enabled on most of builds for SKR boards. On old stock boards there is not enough flash for that feature.
