### ISSUE TITLE
Mega zero btt skr mini mz

### ISSUE THREAD

**Issue by velidhu** [kad/Marlin#8]
I installed the version, anycubic_mega_zero_btt-2.0.7.2-firmware. I noticed that the print recovery does not work after power failure.

**Comment by kad** [comment]
It is disabled by default. In menu->configuration there is option "power recovery", click enable and "store settings".
However, just a reminder, that this functionality in Marlin means extensive wear off for SD card.

**Comment by velidhu** [comment]
thanks for those like me who are not able to compile the firmware
